version: '3.8'

services:
  # LiveKit Server (for local development)
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
    environment:
      LIVEKIT_CONFIG: |
        port: 7880
        rtc:
          tcp_port: 7881
          use_external_ip: true
        keys:
          devkey: secret
          devsecret: secret
        development: true
    command: --config /etc/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml

  # Backend API
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - LIVEKIT_URL=wss://localhost:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - TWILIO_TARGET_PHONE=${TWILIO_TARGET_PHONE}
      - WEBHOOK_BASE_URL=${WEBHOOK_BASE_URL}
    depends_on:
      - livekit
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build: ./apps/web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_LIVEKIT_URL=wss://localhost:7880
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    command: npm run dev

volumes:
  node_modules:
